// regex
export const durakRe = {
  card: /\d+\-\d+/,
};

// selectors
export const selectors = {
  Table: {
    Card: '.front .OneCardSnippet img',
    OneEnemy: '.oneEnemy',
    TrumpCard: '.addClasstrump img',
  },
  MeUser: {
    Card: '.OneMyCard .OneCardSnippet img',
  },
  Users: {
    User1: '#UserByte\\30 ',
    User2: '#UserByte\\31 ',
    User3: '#UserByte\\32 ',
    User4: '#UserByte\\33 ',
    User5: '#UserByte\\34 ',
    User6: '#UserByte\\35 ',
    Pusher: '.IsPushIndicator',
    Defer: '.IsDefIndicator',
  },
  Game: {
    Screen: '.GameWrapper',
    Durak: '.DurakCenter',
    Bura: '.BuraCenter',
    EndGame: '.ModalContent .GameEnd',
    DeckCount: '.TableDeckCount span',
    Options: '.IcoInfo',
    Type: {
      Durak: '.TableType.TableTypeIco1',
      Bura: '.TableType.TableTypeIco2',
      Ochko: '.TableType.TableTypeIco3',
    },
  },
  GardageList: '.GardageList .GargageCard:last-child',
};

export const decks = {
  52: [
    {
      value: '10',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '10-0',
    },
    {
      value: '10',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '10-1',
    },
    {
      value: '10',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '10-2',
    },
    {
      value: '10',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '10-3',
    },
    {
      value: 'В',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '11-0',
    },
    {
      value: 'В',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '11-1',
    },
    {
      value: 'В',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '11-2',
    },
    {
      value: 'В',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '11-3',
    },
    {
      value: 'Д',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '12-0',
    },
    {
      value: 'Д',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '12-1',
    },
    {
      value: 'Д',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '12-2',
    },
    {
      value: 'Д',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '12-3',
    },
    {
      value: 'K',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '13-0',
    },
    {
      value: 'K',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '13-1',
    },
    {
      value: 'K',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '13-2',
    },
    {
      value: 'K',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '13-3',
    },
    {
      value: 'Т',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '14-0',
    },
    {
      value: 'Т',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '14-1',
    },
    {
      value: 'Т',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '14-2',
    },
    {
      value: 'Т',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '14-3',
    },
    {
      value: '2',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '2-0',
    },
    {
      value: '2',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '2-1',
    },
    {
      value: '2',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '2-2',
    },
    {
      value: '2',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '2-3',
    },
    {
      value: '3',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '3-0',
    },
    {
      value: '3',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '3-1',
    },
    {
      value: '3',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '3-2',
    },
    {
      value: '3',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '3-3',
    },
    {
      value: '4',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '4-0',
    },
    {
      value: '4',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '4-1',
    },
    {
      value: '4',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '4-2',
    },
    {
      value: '4',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '4-3',
    },
    {
      value: '5',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '5-0',
    },
    {
      value: '5',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '5-1',
    },
    {
      value: '5',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '5-2',
    },
    {
      value: '5',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '5-3',
    },
    {
      value: '6',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '6-0',
    },
    {
      value: '6',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '6-1',
    },
    {
      value: '6',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '6-2',
    },
    {
      value: '6',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '6-3',
    },
    {
      value: '7',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '7-0',
    },
    {
      value: '7',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '7-1',
    },
    {
      value: '7',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '7-2',
    },
    {
      value: '7',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '7-3',
    },
    {
      value: '8',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '8-0',
    },
    {
      value: '8',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '8-1',
    },
    {
      value: '8',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '8-2',
    },
    {
      value: '8',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '8-3',
    },
    {
      value: '9',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '9-0',
    },
    {
      value: '9',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '9-1',
    },
    {
      value: '9',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '9-2',
    },
    {
      value: '9',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '9-3',
    },
  ],

  36: [
    {
      value: '10',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '10-0',
    },
    {
      value: '10',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '10-1',
    },
    {
      value: '10',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '10-2',
    },
    {
      value: '10',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '10-3',
    },
    {
      value: 'В',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '11-0',
    },
    {
      value: 'В',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '11-1',
    },
    {
      value: 'В',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '11-2',
    },
    {
      value: 'В',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '11-3',
    },
    {
      value: 'Д',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '12-0',
    },
    {
      value: 'Д',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '12-1',
    },
    {
      value: 'Д',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '12-2',
    },
    {
      value: 'Д',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '12-3',
    },
    {
      value: 'K',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '13-0',
    },
    {
      value: 'K',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '13-1',
    },
    {
      value: 'K',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '13-2',
    },
    {
      value: 'K',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '13-3',
    },
    {
      value: 'Т',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '14-0',
    },
    {
      value: 'Т',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '14-1',
    },
    {
      value: 'Т',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '14-2',
    },
    {
      value: 'Т',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '14-3',
    },
    {
      value: '6',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '6-0',
    },
    {
      value: '6',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '6-1',
    },
    {
      value: '6',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '6-2',
    },
    {
      value: '6',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '6-3',
    },
    {
      value: '7',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '7-0',
    },
    {
      value: '7',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '7-1',
    },
    {
      value: '7',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '7-2',
    },
    {
      value: '7',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '7-3',
    },
    {
      value: '8',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '8-0',
    },
    {
      value: '8',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '8-1',
    },
    {
      value: '8',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '8-2',
    },
    {
      value: '8',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '8-3',
    },
    {
      value: '9',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '9-0',
    },
    {
      value: '9',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '9-1',
    },
    {
      value: '9',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '9-2',
    },
    {
      value: '9',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '9-3',
    },
  ],

  24: [
    {
      value: '10',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '10-0',
    },
    {
      value: '10',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '10-1',
    },
    {
      value: '10',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '10-2',
    },
    {
      value: '10',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '10-3',
    },
    {
      value: 'В',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '11-0',
    },
    {
      value: 'В',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '11-1',
    },
    {
      value: 'В',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '11-2',
    },
    {
      value: 'В',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '11-3',
    },
    {
      value: 'Д',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '12-0',
    },
    {
      value: 'Д',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '12-1',
    },
    {
      value: 'Д',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '12-2',
    },
    {
      value: 'Д',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '12-3',
    },
    {
      value: 'K',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '13-0',
    },
    {
      value: 'K',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '13-1',
    },
    {
      value: 'K',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '13-2',
    },
    {
      value: 'K',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '13-3',
    },
    {
      value: 'Т',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '14-0',
    },
    {
      value: 'Т',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '14-1',
    },
    {
      value: 'Т',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '14-2',
    },
    {
      value: 'Т',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '14-3',
    },
    {
      value: '9',
      suit: 'hearts',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '9-0',
    },
    {
      value: '9',
      suit: 'diamonds',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '9-1',
    },
    {
      value: '9',
      suit: 'clubs',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '9-2',
    },
    {
      value: '9',
      suit: 'spades',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      whose: '',
      id: '9-3',
    },
  ],
};
