export default initialState = {
  ids: [
    '2-2',
    '2-3',
    '2-1',
    '2-0',
    '3-0',
    '3-3',
    '3-2',
    '3-1',
    '4-2',
    '4-0',
    '4-3',
    '4-1',
    '5-3',
    '5-1',
    '5-2',
    '5-0',
    '6-2',
    '6-3',
    '6-0',
    '6-1',
    '7-2',
    '7-0',
    '7-3',
    '7-1',
    '8-2',
    '8-1',
    '8-0',
    '8-3',
    '9-0',
    '9-3',
    '9-2',
    '9-1',
    '10-0',
    '10-2',
    '10-3',
    '10-1',
    '11-2',
    '11-3',
    '11-0',
    '11-1',
    '12-2',
    '12-3',
    '12-0',
    '12-1',
    '13-3',
    '13-0',
    '13-1',
    '13-2',
    '14-0',
    '14-3',
    '14-2',
    '14-1',
  ],
  entities: {
    '2-2': {
      name: '2',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '2-2',
      type: 2,
      value: 2,
    },
    '2-3': {
      name: '2',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '2-3',
      type: 3,
      value: 2,
    },
    '2-1': {
      name: '2',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '2-1',
      type: 1,
      value: 2,
    },
    '2-0': {
      name: '2',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '2-0',
      type: 0,
      value: 2,
    },
    '3-0': {
      name: '3',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '3-0',
      type: 0,
      value: 3,
    },
    '3-3': {
      name: '3',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '3-3',
      type: 3,
      value: 3,
    },
    '3-2': {
      name: '3',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '3-2',
      type: 2,
      value: 3,
    },
    '3-1': {
      name: '3',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '3-1',
      type: 1,
      value: 3,
    },
    '4-2': {
      name: '4',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '4-2',
      type: 2,
      value: 4,
    },
    '4-0': {
      name: '4',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '4-0',
      type: 0,
      value: 4,
    },
    '4-3': {
      name: '4',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '4-3',
      type: 3,
      value: 4,
    },
    '4-1': {
      name: '4',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '4-1',
      type: 1,
      value: 4,
    },
    '5-3': {
      name: '5',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '5-3',
      type: 3,
      value: 5,
    },
    '5-1': {
      name: '5',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '5-1',
      type: 1,
      value: 5,
    },
    '5-2': {
      name: '5',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '5-2',
      type: 2,
      value: 5,
    },
    '5-0': {
      name: '5',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '5-0',
      type: 0,
      value: 5,
    },
    '6-2': {
      name: '6',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '6-2',
      type: 2,
      value: 6,
    },
    '6-3': {
      name: '6',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '6-3',
      type: 3,
      value: 6,
    },
    '6-0': {
      name: '6',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '6-0',
      type: 0,
      value: 6,
    },
    '6-1': {
      name: '6',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '6-1',
      type: 1,
      value: 6,
    },
    '7-2': {
      name: '7',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '7-2',
      type: 2,
      value: 7,
    },
    '7-0': {
      name: '7',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '7-0',
      type: 0,
      value: 7,
    },
    '7-3': {
      name: '7',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '7-3',
      type: 3,
      value: 7,
    },
    '7-1': {
      name: '7',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '7-1',
      type: 1,
      value: 7,
    },
    '8-2': {
      name: '8',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '8-2',
      type: 2,
      value: 8,
    },
    '8-1': {
      name: '8',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '8-1',
      type: 1,
      value: 8,
    },
    '8-0': {
      name: '8',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '8-0',
      type: 0,
      value: 8,
    },
    '8-3': {
      name: '8',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '8-3',
      type: 3,
      value: 8,
    },
    '9-0': {
      name: '9',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '9-0',
      type: 0,
      value: 9,
    },
    '9-3': {
      name: '9',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '9-3',
      type: 3,
      value: 9,
    },
    '9-2': {
      name: '9',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '9-2',
      type: 2,
      value: 9,
    },
    '9-1': {
      name: '9',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '9-1',
      type: 1,
      value: 9,
    },
    '10-0': {
      name: '10',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '10-0',
      type: 0,
      value: 10,
    },
    '10-2': {
      name: '10',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '10-2',
      type: 2,
      value: 10,
    },
    '10-3': {
      name: '10',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '10-3',
      type: 3,
      value: 10,
    },
    '10-1': {
      name: '10',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '10-1',
      type: 1,
      value: 10,
    },
    '11-2': {
      name: 'В',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '11-2',
      type: 2,
      value: 11,
    },
    '11-3': {
      name: 'В',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '11-3',
      type: 3,
      value: 11,
    },
    '11-0': {
      name: 'В',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '11-0',
      type: 0,
      value: 11,
    },
    '11-1': {
      name: 'В',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '11-1',
      type: 1,
      value: 11,
    },
    '12-2': {
      name: 'Д',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '12-2',
      type: 2,
      value: 12,
    },
    '12-3': {
      name: 'Д',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '12-3',
      type: 3,
      value: 12,
    },
    '12-0': {
      name: 'Д',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '12-0',
      type: 0,
      value: 12,
    },
    '12-1': {
      name: 'Д',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '12-1',
      type: 1,
      value: 12,
    },
    '13-3': {
      name: 'K',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '13-3',
      type: 3,
      value: 13,
    },
    '13-0': {
      name: 'K',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '13-0',
      type: 0,
      value: 13,
    },
    '13-1': {
      name: 'K',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '13-1',
      type: 1,
      value: 13,
    },
    '13-2': {
      name: 'K',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '13-2',
      type: 2,
      value: 13,
    },
    '14-0': {
      name: 'Т',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '14-0',
      type: 0,
      value: 14,
    },
    '14-3': {
      name: 'Т',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '14-3',
      type: 3,
      value: 14,
    },
    '14-2': {
      name: 'Т',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '14-2',
      type: 2,
      value: 14,
    },
    '14-1': {
      name: 'Т',
      ontable: false,
      onhands: false,
      discard: false,
      trump: false,
      hostile: false,
      indeck: true,
      owner: { userId: null, position: null },
      id: '14-1',
      type: 1,
      value: 14,
    },
  },
};
